spring:
  application:
    name: travel-service

  #datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel_db?rewriteBatchedStatements=true
    username: root
    password: wngur9836

  #redis
#  data:
#    redis:
#      host: localhost
#      port: 6379

  #jpa
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  #security
  profiles:
    include: secret

# eureka
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8004