server:
  port: 8004
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: local
  application:
    name: travel-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

# local 프로필
---

spring:

  config:
    activate:
      on-profile: local

  cloud:
    kubernetes:
      enabled: false

  #datasource
  datasource:
    url: jdbc:mysql://localhost:3306/travel_db
    username: root
    password: wngur9836

  #redis
  data:
    redis:
      host: host
      port: 6379

# eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

# develop 프로필
---
spring:

  config:
    activate:
      on-profile: develop

  #datasource
  datasource:
    url: '${MYSQL_URL}/travel_service'
    username: "${MYSQL_USERNAME}"
    password: "${MYSQL_PASSWORD}"
    hikari:

      data-source-properties:
        rewriteBatchStatements: true

  #redis
  data:
    redis:
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"
      password: "${REDIS_PASSWORD}"

eureka:
  client:
    enabled: true